# /etc/nginx/conf.d/default.conf

server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;
    client_max_body_size 12M;

    # Laravel backend
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location /hot {
    proxy_pass http://laravel-app:5173;
    }
        location ~ \.php$ {
        fastcgi_pass laravel-app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Vite dev assets
    location /@vite/ {
        proxy_pass http://laravel-app:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /resources/ {
        proxy_pass http://laravel-app:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}