<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SongsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $songs = [
            [
                'title' => 'Fly Away',
                'artist' => 'TheFatRat',
                'album' => 'Parallax',
                'file_name' => 'FLY AWAY.mp3',
                'cover_url' => 'songCovers/FLY AWAY.jpg',
                'duration' => 215,
                'release_date' => '2020-03-15',
            ],
            [
                'title' => 'Mayday',
                'artist' => 'TheFatRat',
                'album' => 'Parallax',
                'file_name' => 'MAYDAY.mp3',
                'cover_url' => 'songCovers/MAYDAY.jpg',
                'duration' => 190,
                'release_date' => '2019-07-22',
            ],
            [
                'title' => 'Rise Up',
                'artist' => 'TheFatRat',
                'album' => 'Rising Sun',
                'file_name' => 'RISE UP.mp3',
                'cover_url' => 'songCovers/RISE UP.jpg',
                'duration' => 185,
                'release_date' => '2021-01-10',
            ],
            [
                'title' => 'Unity',
                'artist' => 'TheFatRat',
                'album' => 'Unity',
                'file_name' => 'UNITY.mp3',
                'cover_url' => 'songCovers/UNITY.jpg',
                'duration' => 260,
                'release_date' => '2018-11-05',
            ],
            [
                'title' => 'Xenogenesis',
                'artist' => 'TheFatRat',
                'album' => 'Xenogenesis',
                'file_name' => 'XENOGENESIS.mp3',
                'cover_url' => 'songCovers/XENOGENESIS.jpg',
                'duration' => 255,
                'release_date' => '2022-06-30',
            ],
            [
                'title' => 'Monody',
                'artist' => 'TheFatRat',
                'album' => 'Monody',
                'file_name' => 'MONODY.mp3',
                'cover_url' => 'songCovers/MONODY.jpg',
                'duration' => 291,
                'release_date' => '2015-11-07',
            ],
            [
                'title' => 'No No No',
                'artist' => 'TheFatRat',
                'album' => 'No No No',
                'file_name' => 'NO NO NO.mp3',
                'cover_url' => 'songCovers/NO NO NO.jpg',
                'duration' => 186,
                'release_date' => '2016-06-15',
            ],
            [
                'title' => 'Ray Tracer',
                'artist' => 'TheFatRat',
                'album' => 'Ray Tracer - EP',
                'file_name' => 'RAY TRACER.mp3',
                'cover_url' => 'songCovers/RAY TRACER.jpg',
                'duration' => 229,
                'release_date' => '2024-09-27',
            ],
            [
                'title' => 'Sail Away',
                'artist' => 'TheFatRat',
                'album' => 'Sail Away',
                'file_name' => 'SAIL AWAY.mp3',
                'cover_url' => 'songCovers/SAIL AWAY.jpg',
                'duration' => 183,
                'release_date' => '2024-01-26',
            ],
            [
                'title' => 'P. S.',
                'artist' => 'TheFatRat',
                'album' => 'Ray Tracer - EP',
                'file_name' => 'PS.mp3',
                'cover_url' => 'songCovers/PS.jpg',
                'duration' => 157,
                'release_date' => '2024-09-27',
            ],
            [
                'title' => 'Myself & I',
                'artist' => 'TheFatRat',
                'album' => 'Parallax',
                'file_name' => 'MYSELF AND I.mp3',
                'cover_url' => 'songCovers/MYSELF AND I.jpg',
                'duration' => 188,
                'release_date' => '2021-08-20',
            ],
            [
                'title' => 'Monkeys',
                'artist' => 'TheFatRat',
                'album' => 'Monkeys',
                'file_name' => 'MONKEYS.mp3',
                'cover_url' => 'songCovers/MONKEYS.jpg',
                'duration' => 163,
                'release_date' => '2024-04-12',
            ],
            [
                'title' => 'Out of the Rain',
                'artist' => 'TheFatRat',
                'album' => 'Out of the Rain',
                'file_name' => 'OUT OF THE RAIN.mp3',
                'cover_url' => 'songCovers/OUT OF THE RAIN.jpg',
                'duration' => 196,
                'release_date' => '2023-04-28',
            ],
            [
                'title' => 'Hunger',
                'artist' => 'TheFatRat',
                'album' => 'Hunger',
                'file_name' => 'HUNGER.mp3',
                'cover_url' => 'songCovers/HUNGER.jpg',
                'duration' => 182,
                'release_date' => '2024-11-22',
            ],
            [
                'title' => 'Escaping Gravity',
                'artist' => 'TheFatRat',
                'album' => 'Escaping Gravity',
                'file_name' => 'ESCAPING GRAVITY.mp3',
                'cover_url' => 'songCovers/ESCAPING GRAVITY.jpg',
                'duration' => 171,
                'release_date' => '2025-01-24',
            ],

            [
                'title' => 'Hellcat',
                'artist' => 'NCS',
                'album' => 'NCS: The Best of 2014',
                'file_name' => 'Hellcat.mp3',
                'cover_url' => 'songCovers/HELLCAT.jpg',
                'duration' => 255,
                'release_date' => '2014-01-01',
            ],
            [
                'title' => 'Heroes Tonight',
                'artist' => 'NCS',
                'album' => 'NCS: Heroes',
                'file_name' => 'Heroes Tonight.mp3',
                'cover_url' => 'songCovers/HEROES TONIGHT.jpg',
                'duration' => 255,
                'release_date' => '2015-12-01',
            ],
            [
                'title' => 'Mortals',
                'artist' => 'NCS',
                'album' => 'NCS: Infinity',
                'file_name' => 'Mortals.mp3',
                'cover_url' => 'songCovers/MORTALS.jpg',
                'duration' => 255,
                'release_date' => '2016-08-01',
            ],
            [
                'title' => 'On & On',
                'artist' => 'NCS',
                'album' => 'NCS: On & On',
                'file_name' => 'On & On.mp3',
                'cover_url' => 'songCovers/ON&ON.jpg',
                'duration' => 255,
                'release_date' => '2014-07-01',
            ],
            [
                'title' => 'Nekozilla',
                'artist' => 'NCS',
                'album' => 'NCS: Nekozilla',
                'file_name' => 'Nekozilla.mp3',
                'cover_url' => 'songCovers/NEKOZILLA.jpg',
                'duration' => 166,
                'release_date' => '2015-09-04',
            ],
            [
                'title' => 'My Heart',
                'artist' => 'NCS',
                'album' => 'NCS: The Best of 2014',
                'file_name' => 'My Heart.mp3',
                'cover_url' => 'songCovers/MY HEART.jpg',
                'duration' => 268,
                'release_date' => '2014-11-13',
            ],
            [
                'title' => 'Sky High',
                'artist' => 'NCS',
                'album' => 'NCS: The Best of 2016',
                'file_name' => 'Sky High.mp3',
                'cover_url' => 'songCovers/SKY HIGH.jpg',
                'duration' => 238,
                'release_date' => '2016-12-28',
            ],
            [
                'title' => 'Shine',
                'artist' => 'NCS',
                'album' => 'NCS: The Best of 2013',
                'file_name' => 'Shine.mp3',
                'cover_url' => 'songCovers/SHINE.png',
                'duration' => 260,
                'release_date' => '2013-05-05',
            ],
            [
                'title' => 'Symbolism',
                'artist' => 'NCS',
                'album' => 'NCS: The Best of 2014',
                'file_name' => 'Symbolism.mp3',
                'cover_url' => 'songCovers/SYMBOLISM.jpg',
                'duration' => 291,
                'release_date' => '2014-11-27',
            ],
            [
                'title' => 'Tropic Love',
                'artist' => 'NCS',
                'album' => 'NCS: The Best of 2015',
                'file_name' => 'Tropic Love.mp3',
                'cover_url' => 'songCovers/TROPIC LOVE.jpg',
                'duration' => 281,
                'release_date' => '2015-12-23',
            ],

            [
                'title' => 'Mesmerizing Galaxy',
                'artist' => 'Kevin MacLeod',
                'album' => 'Oddities (Everything Else)',
                'file_name' => 'MESMERIZING GALAXY.mp3',
                'cover_url' => 'songCovers/MESMERIZING GALAXY.jpg',
                'duration' => 92,
                'release_date' => '2023-11-28',
            ],
            [
                'title' => 'Galactic Rap',
                'artist' => 'Kevin MacLeod',
                'album' => 'Mystery (Film Scoring Moods)',
                'file_name' => 'GALACTIC RAP.mp3',
                'cover_url' => 'songCovers/GALACTIC RAP.jpg',
                'duration' => 142,
                'release_date' => '2023-11-28',
            ],
            [
                'title' => 'Cloud Dancer',
                'artist' => 'Kevin MacLeod',
                'album' => 'Video Classica (Electronic and Rock)',
                'file_name' => 'CLOUD DANCER.mp3',
                'cover_url' => 'songCovers/CLOUD DANCER.jpg',
                'duration' => 220,
                'release_date' => '2023-11-28',
            ],
            [
                'title' => 'Brain Dance',
                'artist' => 'Kevin MacLeod',
                'album' => 'Jazz (Everything Else)',
                'file_name' => 'BRAIN DANCE.mp3',
                'cover_url' => 'songCovers/BRAIN DANCE.jpg',
                'duration' => 215,
                'release_date' => '2023-11-28',
            ],
        ];

        foreach ($songs as $song) {
            DB::table('songs')->insert([
                'uuid' => Str::uuid(),
                'title' => $song['title'],
                'artist' => $song['artist'],
                'album' => $song['album'],
                'file_name' => $song['file_name'],
                'cover_url' => 'storage/' . $song['cover_url'],
                'date' => $song['release_date'],
                'created_at' => now(),
                'duration' => $song['duration'],
                'genre' => 'Electronic',
            ]);
        }
    }
}
